% Returns the model parameters according to the type
% Yan Peng, UBC, 2016/10/20

%Changed to a 45nm MOSFET model an added junction capacitance parameters
% Justin Reiher 2017/07/30

function [input_params] = ekv_model_params_45nmHP(type)

%% Define parameters for the model
% This is a 45nm mosfet model

switch(type)
    case 'n'
        input_params = struct('version',    1,...
                              'Io', 1.6276,  ...
                              'Vth', 0.5374, ...
                              'alpha', 13.1665, ...
                              'beta',  0.1573, ...
                              'W', 450e-7,...
                              'Lg', 45e-7,...
                              'Tjun',298,...
                              'gamma', 0.0266,...
                              'phi',  0.5181,...
                              'type',1);
    case 'p'
        input_params = struct('version',    1,...
                              'Io', -1.2253,  ...
                              'Vth', -0.4371, ...
                              'alpha', -13.2519, ...
                              'beta',  0.2125, ...
                              'W', 450e-7,...
                              'Lg', 45e-7,...
                              'Tjun',298,...
                              'gamma',0.0288,...
                              'phi', 0.5601,...
                              'type',-1);
    case 'baseCap'
        input_params = 2.57e-6;
    case 'capScale'
        input_params = 2.2;
    case 'junc'
        input_params = struct('TNOM',        300,        'Wint',     5e-7,       ...
            'Lgdr',        45e-7,      'dLg',       3.75e-7,    ...
            'Xl',          -20e-9,     'Xw',       0,          ...
            'Xj',          1.4e-6,     'CjdTnom',  0.0005,  ...
            'Tjun',        298,        'Tcj',      0.001,   ...
            'PbdTnom',     1.0,       'Tpb',       0.005,  ...
            'CjswdTnom',   5e-10,     'Tcjsw',     0.001,  ...
            'PbswdTnom',   1.0,       'Tpbsw',     0.005,  ...
            'CjswgdTnom', 5e-10,      'Tcjswg',    0.001, ...
            'PbswgdTnom',  1.0,       'Tpbswg',    0.005, ...
            'Mjd',        0.5,        'Mjswd',    0.33,   ...
            'Mjswgd',     0.33,          'W',     450e-7);
    otherwise
        fprintf('Available Parameters:\n "n" for nmos device params, \n "p" for pmos device params, \n "baseCap" for base Capacitance in F/cm^2, \n "junCapParams" for parameters to compute junction capacitance');
        
        
        
end

end